name: Checkov Security Scan

on:
  pull_request:
    branches:
      - main  # Run on PRs targeting 'main'

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@12
        with:
          directory: "."
          skip_path: .*test.*
          skip_check: CKV_K8S_21
          quiet: true
          output_format: cli,sarif
          output_file_path: console,results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: results.sarif          
