name: Checkov Security Scan

on:
  pull_request:
    branches:
      - main  # Run on PRs targeting 'main'

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: "."
          skip_path: .*test.*
          skip_check: CKV_K8S_21
          output_format: github_failed_only



