name: Checkov Security Scan

on:
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3

      - name: Extract Repo Name as Variable
        id: extract_repo
        run: echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

      - name: Show Files for Debug
        run: |
          echo "Repo name: $REPO_NAME"
          echo "### Current Working Directory"
          pwd
          
          echo "### Top-level ls"
          ls -al          
          echo "---"
          find . | grep .github

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: "${{ env.REPO_NAME }}"
          output_format: "github_failed_only"
          skip_path: ".*test.*"

#  skip_path: "^${{ env.REPO_NAME }}/.*test.*$|^${{ env.REPO_NAME }}/\\.github.*$"